### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by thinklikeadesigner** [DianaSuvorova/ufo-explorer#31]
These should all be quick fixes if anyone is down

<img width="1342" alt="Screen Shot 2021-09-19 at 2 04 13 PM" src="https://user-images.githubusercontent.com/58955802/133940153-96d1f717-b00c-4afc-861d-b44b547d263a.png">
<img width="1330" alt="Screen Shot 2021-09-19 at 2 01 32 PM" src="https://user-images.githubusercontent.com/58955802/133940155-5155a839-2455-4b77-bce8-62b8e1573c07.png">
<img width="1009" alt="Screen Shot 2021-09-19 at 1 59 49 PM" src="https://user-images.githubusercontent.com/58955802/133940156-c219415c-167c-44c7-85ef-1a30b4a7d43a.png">
<img width="1030" alt="Screen Shot 2021-09-19 at 2 12 37 PM" src="https://user-images.githubusercontent.com/58955802/133940158-dac6f136-cf65-433a-a742-044d23f198e1.png">

**Comment by DianaSuvorova** [comment]
Thank you  @thinklikeadesigner !

**Comment by thinklikeadesigner** [comment]
There also seems to be a weird margin here

<img width="1308" alt="Screen Shot 2021-09-19 at 2 40 06 PM" src="https://user-images.githubusercontent.com/58955802/133940772-c5b284d1-5759-4563-8c46-686b9b5f6aab.png">

**Comment by DianaSuvorova** [comment]
Reg last one -> what is weird about this margin? What do you think it should be?

**Comment by thinklikeadesigner** [comment]
the ```header``` and ```footer``` have a horizontal padding of 130px. 
the 20px margin on ```main``` is pushing the content to the right, so to compensate the horizontal padding for ```main``` is only 105px.

here's a visual representation of what the margin is doing
```header```
 --->```main```
```footer```
In order for each section to line up horizontally, I propose a ```section``` class with a single horizontal padding, and at that point you just wrap ```header```, ```footer```, and ```main``` in this ```section``` utility class

Usually when there's a margin, there's a reason for it. The margin in this case, is causing misalignment, and making it so you have to use unique values for main that you don't need to use for header and footer. so when you make a change in one place, you have to remember to make the change everywhere else.

**Comment by DianaSuvorova** [comment]
I see, that's very good structure you laid out. Yes, we should fix that.

**Comment by DianaSuvorova** [comment]
@thinklikeadesigner 

I have approved/merged your PR. Were all of the issues fixed in there? or there some remaining?
